services:
  apache:
    image: httpd:latest  # Imagen oficial de Apache en DockerHub
    container_name: apache_server
    ports:
      - "80:80"  # Expone Apache en el puerto 80
    volumes:
      - ./html:/usr/local/apache2/htdocs  # Monta un directorio local como raíz web
